{% set name = "pyiron_vasp" %}
{% set version = "0.2.6" %}
{% set sha256 = "70fe23c429405c80a6918d79df714516bdcef5363c77b67378bf53459ee651fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
    - toml
    - ase
    - defusedxml
    - numpy
    - pandas
    - scipy
  run:
    - python >={{ python_min }}
    - ase >=3.22.1,<=3.25.0
    - defusedxml >=0.7.0,<=0.7.1
    - numpy >=1.26.0,<=2.2.4
    - pandas >=2.0.3,<=2.3.0
    - scipy >=1.11.1,<=1.15.2

test:
  imports:
    - pyiron_vasp
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pyiron_vasp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Vasp plugin for pyiron - an integrated development environment (IDE) for computational materials science.'
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
