travis:
  secure:
    BINSTAR_TOKEN: LUKwDhUQ/6hsk0HWAvNfJQwOnkQlsT/PT84pdT/e+gxbt0DOY/0INZ96UFLJq2WDR3w9rbvn+4Hcb/1a1LFqhgrfwVVkWw9SkbF2LmQx/E+9Akn34xcwhBJc1tqDzhOWCe2W/tTQa9fhDHnJTA3oFwJqUqrIrTVNjnasAhrWcg1ffUMQWPeA08v6x6SBE6+342fc1mHMVRAh+TbXihL6k+Rrpx7QD6BPQtKI9kO2oi2femZTQkN3EVWN6JyNj28Stk218oOZ2QtkkPjZ/tf2Van0GYfo5CxxBYzDZz4qIMWf2mnkZzbe/jQUqIEZJRnQfjHOEA2q6DZmKtn86wTt2+yFcIrTWmoUs+T9qaAxc/kUybrFazQMUb6Evq6n4k5081Mfirc6yPt15eC8ybnbFm+LnSRxac+rulyQCZs/crrxv1gQoOysFpxTNN4bTeJHjwsIPDAV4rGhXTpHx5M7gRVHLfQqaidfiIzsFZuVkSyS8upMkEXkVgLJw3/nlSmQYf6bnlnjjnWUnYVhKeUAai4AA8ICgs1vUVDUQB4hD4u8WExz/6RO1YRmmfmAvfEoU87F6HU2iAItBPabPkL1dM4L36B31DvZqc3fiYvYhK1tH3HY8ZSTajdtbaz/QKU0kCm1h+X3vCcHCHpOhf3b5ckGWrsPQl+BxLNSHSq21cI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
