travis:
  secure:
    BINSTAR_TOKEN: R9gtuv0ljAWdwSMOPQ59stGzq8R3ik34ET/QTvfHupnGGEjnytDxGmaObUJFINcoewVObz+bWmShcpcb9kGx3j00KvgJIJQ3s4idv46jddQP7r2JjsIe3LZ0FHv7s5J/Z23c+zpgh1sLiT+FRNbZTRmFKzzbBS1cfGrEYAjYG4EJd/FCxiIs7OP9+4nKpg/JqVMsDVXE23aZ7rilLyL+JsLantRK2BPhhSNL0AzPJvC74wP/GOlk+ZzE5XgtoOPtS9nqXfsFRVU2nmVuTNaE2Vl32m3+cy4Dhaqij+v3DJYfIjcgBxdSbc2yW1taPJdinVwMYQhda93yj3j5g+XSYbobId8hz17mer9gMI0saXfdnyHdgVBpisgXlVkajJnfF+oLhgQFTLDqZH+CTTZo3WeURW7LHCmBFR+cZ7GGto5EGmoB14DOLg4IxBGhDlIqE26XiQRwEZhvD7ttXnHfeuLsE8vGALq6n7shwDpMsVw20aOkyGpRqlGwWy57SB7siRsE+D9EinquX8i7ewoicbrxuCzhvG+E3y2jVTst7h+wAi1aCI5TZiqkPUkEHdIzWJcc8bfPlOcYHSyYctWvSgjuCYY8wa6bLz+S4M2KOzkL4H1Nth4OCnr9tMJJiMeIYQqKdtHH2I3iUTalHKJCgZ6blfgLmd1+wcgnTWII4QM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
